base_url = "https://lucy-dalzell.superhi.hosting/"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = true

[extra]
thumbnail_width = 800
thumbnail_height = 600
thumbnail_format = "webp" # auto, jpg, png, webp
thumbnail_quality = 90 # %
